import { Option } from '@/components/ui/multiselect';
import {
  AreaChart,
  BarChart,
  FolderCheck,
  LineChart,
  PieChart,
  SquareAsterisk,
  Table,
} from 'lucide-react';
export const formatLabel = (label: string) =>
  label.replace(/([a-z])([A-Z])/g, '$1 $2');

export const fontStyleTypes = ['normalize', 'italic', 'oblique'];
export const fontWeightTypes = ['normal', 'bold', 'bolder', 'lighter'];
export const LinePalettes = [
  '#5470c6',
  '#91cc75',
  '#fac858',
  '#ee6666',
  '#73c0de',
  '#3ba272',
  '#fc8452',
  '#9a60b4',
  '#ea7ccc',
];

export const DisplayOptions: Option[] = [
  { value: 'Dimensions', label: 'Dimensions' },
  { value: 'ForceCategorical', label: 'Force categorical' },
  { value: 'Filters', label: 'Filters' },
  { value: 'RowLimit', label: 'Row limit' },
  { value: 'SortBy', label: 'Sort by' },
  { value: 'Subheader', label: 'Subheader' },
  { value: 'X-axis', label: 'X-axis' },
  { value: 'X-AxisSortBy', label: 'X-Axis Sort By' },
  { value: 'ContributionMode', label: 'Contribution Mode' },
  { value: 'Series limit', label: 'Series limit' },
  { value: 'SortQueryBy', label: 'Sort query by' },
  { value: 'TruncateMetric', label: 'Truncate Metric' },
  { value: 'ShowEmptyColumns', label: 'Show empty columns' },
];
export const CustomizationOptions: Option[] = [
  { value: 'textStyle', label: 'Text Style' },
  { value: 'aria', label: 'Aria' },
  { value: 'colorPlatte', label: 'Color Platte' },
  { value: 'gradientColor', label: 'Gradient Color' },
  { value: 'stateAnimation', label: 'State Animation' },
  { value: 'animation', label: 'Animation' },
  { value: 'animationDuration', label: 'Animation Duration' },
  { value: 'animationDurationUpdate', label: 'Animation Duration Update' },
  { value: 'animationEasing', label: 'Animation Easing' },
  { value: 'animationEasingUpdate', label: 'Animation Easing Update:' },
  { value: 'animationThreshold', label: 'Animation Threshold' },
  { value: 'progressiveThreshold', label: 'Progressive Threshold' },
  { value: 'progressive', label: 'Progressive' },
  { value: 'hoverLayerThreshold', label: 'hover Layer Threshold' },
  { value: 'useUTC', label: 'Use UTC' },
  { value: 'title', label: 'Title' },
  { value: 'axisPointer', label: 'Axis Pointer' },
  { value: 'tooltip', label: 'Tooltipr' },
  { value: 'legend', label: 'Legend' },
  { value: 'yAxis', label: 'Y Axis' },
  { value: 'xAxis', label: ' X Axis' },
  { value: 'grid', label: 'Grid' },
  { value: "BigNumberFontSize", label: "Big Number Font Size" },
  { value: "SubheaderFontSize", label: "Subheader Font Size" },
  { value: "NumberFormat", label: "Number format" },
  { value: "CurrencyFormat", label: "Currency format" },
  { value: "Currency", label: "Currency" },
  { value: "DateFormat", label: "Date format" },
  { value: "ForceDateFormat", label: "Force date format" },
  { value: "ColorScheme", label: "Color Scheme" },
  { value: "PercentageThreshold", label: "Percentage threshold" },
  { value: "RoseType", label: "Rose Type" },
  { value: "Legend", label: "Legend" },
  { value: "Type", label: "Type" },
  { value: "Orientation", label: "Orientation" },
  { value: "Margin", label: "Margin" },
  { value: "LabelType", label: "Label Type" },
  { value: "ShowLabels", label: "Show Labels" },
  { value: "PutLabelsOutside", label: "Put labels outside" },
  { value: "LabelLine", label: "Label Line" },
  { value: "ShowTotal", label: "Show Total" },
  { value: "OuterRadius", label: "Outer Radius" },
  { value: "Donut", label: "Donut" },
  { value: "Subtitle", label: "Subtitle" },
  { value: "BarOrientation", label: "Bar orientation" },
  { value: "AxisTitle", label: "Axis Title" },
  { value: "AXISTITLEMARGIN", label: "AXIS TITLE MARGIN" },
  { value: "AXISTITLEPOSITION", label: "AXIS TITLE POSITION" },
  { value: "SortSeriesBy", label: "Sort Series By" },
  { value: "SortSeriesAscending", label: "Sort Series Ascending" },
  { value: "Show Value", label: "Show Value" },
  { value: "StackedStyle", label: "Stacked Style" },
  { value: "Minorticks", label: "Minor ticks" },
  { value: "DataZoom", label: "Data Zoom" },
  { value: "ShowLegend", label: "Show legend" },
  { value: "TimeFormat", label: "Time format" },
  { value: "RotateXaxisLabel", label: "Rotate x axis label" },
  { value: "TruncateXAxis", label: "Truncate X Axis" },
  { value: "RichTooltip", label: "Rich tooltip" },
  { value: "ShowPercentage", label: "Show percentage" },
  { value: "TooltipSortByMetric", label: "Tooltip sort by metric" },
  { value: "TooltipTimeFormat", label: "Tooltip time format" },
  { value: "AxisFormat", label: "Axis Format" },
  { value: "LogarithmicAxis", label: "Logarithmic axis" },
  { value: "MinorSplitLine", label: "Minor Split Line" },
  { value: "TruncateAxis", label: "Truncate Axis" },
  { value: "XAxisLabelInterval", label: "X Axis Label Interval" },
  { value: "XAxisBounds", label: "X Axis Bounds" },
];
export const IconOptions = [
  { id: 1, value: 'bar', label: 'Bar Chart', icon: <BarChart size={20} /> },
  { id: 2, value: 'pie', label: 'Pie Chart', icon: <PieChart size={20} /> },
  { id: 3, value: 'line', label: 'Line Chart', icon: <LineChart size={20} /> },
  { id: 4, value: 'area', label: 'Area Chart', icon: <AreaChart size={20} /> },
  { id: 5, value: 'table', label: 'Table', icon: <Table size={20} /> },
  {
    id: 6,
    value: 'bignumber',
    label: 'Big number',
    icon: <SquareAsterisk size={20} />,
  },
];

// export const DisplayAndHideOptions: Option[] = [
//   { value: 'Metrics', label: 'Metrics' },
//   { value: 'Dimensions', label: 'Dimensions' },
//   { value: 'Filters', label: 'Filters' },
//   { value: 'RowLimit', label: 'Row limit' },
//   { value: 'SortBy', label: 'Sort by' },
//   { value: 'Subheader', label: 'Subheader' },
//   { value: 'X-axis', label: 'X-axis' },
//   { value: 'X-AxisSortBy', label: 'X-Axis Sort By' },
//   { value: 'ContributionMode', label: 'Contribution Mode' },
//   { value: 'Series limit', label: 'Series limit' },
//   { value: 'SortQueryBy', label: 'Sort query by' },
//   { value: 'TruncateMetric', label: 'Truncate Metric' },
//   { value: 'ShowEmptyColumns', label: 'Show empty columns' },
// ];
